name: CI

on:
  push:
  pull_request:
#  release:
#    types:
#      - published

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !startsWith(github.ref, 'refs/tags/')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: |
          dotnet publish -c Release -f netcoreapp3.1 -r win-x64
          dotnet publish -c Release -f netcoreapp3.1 -r linux-x64
          dotnet build -c Release -f net472
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: SixModLoader.Launcher\bin\Release\