name: CI

on:
  push:
  pull_request:
  release:
    types:
      - published

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, '[skip ci]') && (!startsWith(github.ref, 'refs/tags/') || github.event_name == 'release')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: |
          dotnet publish -c Release -f netcoreapp3.1 -r win-x64
          dotnet publish -c Release -f netcoreapp3.1 -r linux-x64
          dotnet build -c Release -f net472

      - name: Upload netcore-win-x64
        uses: actions/upload-artifact@v2
        with:
          name: netcore-win-x64
          path: SixModLoader.Launcher\bin\Release\netcoreapp3.1\win-x64\publish

      - name: Upload netcore-linux-x64
        uses: actions/upload-artifact@v2
        with:
          name: netcore-linux-x64
          path: SixModLoader.Launcher\bin\Release\netcoreapp3.1\linux-x64\publish

      - name: Upload net472
        uses: actions/upload-artifact@v2
        with:
          name: net472
          path: SixModLoader.Launcher\bin\Release\net472

      - name: Upload netcore-win-x64
        if: ${{ github.event_name == 'release' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: SixModLoader.Launcher\bin\Release\netcoreapp3.1\win-x64\publish
          asset_name: netcore-win-x64
          asset_content_type: application/octet-stream

      - name: Upload netcore-linux-x64
        if: ${{ github.event_name == 'release' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: SixModLoader.Launcher\bin\Release\netcoreapp3.1\linux-x64\publish
          asset_name: netcore-linux-x64
          asset_content_type: application/octet-stream
          
      - name: Upload net472
        if: ${{ github.event_name == 'release' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: SixModLoader.Launcher\bin\Release\net472
          asset_name: net472
          asset_content_type: application/octet-stream      